parameters:
#    acme_sepa_blog.example.class: Acme\SepaBlogBundle\Example

services:
#    acme_sepa_blog.example:
#        class: %acme_sepa_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
